[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "movies_package"
version = "1.0"
authors = [
  {name = "Thomas Anagnostis", email = "anagnostis92t@gmail.com" }
]